In [1]:
%load_ext sql

In [2]:
%sql postgresql://appdev@data:5432/appdev

'Connected: appdev@appdev'

Ex1: Using a single join and a grouping, write a query that allows you to find the forename, surname, driverid and the total number of wins for each driver in the f1db schema.

In [138]:
%%sql SELECT forename, surname, driverid, COUNT(position) AS numberwins 
FROM results INNER JOIN drivers USING (driverid) 
WHERE position = 1 
GROUP BY forename, surname, driverid 
ORDER BY COUNT(position) DESC;

107 rows affected.

[('Michael', 'Schumacher', 30, 91),
 ('Lewis', 'Hamilton', 1, 60),
 ('Alain', 'Prost', 117, 51),
 ('Sebastian', 'Vettel', 20, 46),
 ('Ayrton', 'Senna', 102, 41),
 ('Fernando', 'Alonso', 4, 32),
 ('Nigel', 'Mansell', 95, 31),
 ('Jackie', 'Stewart', 328, 27),
 ('Jim', 'Clark', 373, 25),
 ('Niki', 'Lauda', 182, 25),
 ('Juan', 'Fangio', 579, 24),
 ('Nico', 'Rosberg', 3, 23),
 ('Nelson', 'Piquet', 137, 23),
 ('Damon', 'Hill', 71, 22),
 ('Kimi', 'Räikkönen', 8, 20),
 ('Mika', 'Häkkinen', 57, 20),
 ('Stirling', 'Moss', 475, 16),
 ('Jenson', 'Button', 18, 15),
 ('Graham', 'Hill', 289, 14),
 ('Emerson', 'Fittipaldi', 224, 14),
 ('Jack', 'Brabham', 356, 14),
 ('David', 'Coulthard', 14, 13),
 ('Alberto', 'Ascari', 647, 13),
 ('Alan', 'Jones', 178, 12),
 ('Carlos', 'Reutemann', 199, 12),
 ('Mario', 'Andretti', 207, 12),
 ('Rubens', 'Barrichello', 22, 11),
 ('Jacques', 'Villeneuve', 35, 11),
 ('Felipe', 'Massa', 13, 11),
 ('Jody', 'Scheckter', 222, 10),
 ('James', 'Hunt', 231, 10),
 ('Gerhard', 'Berger', 77, 10),
 ('Ronnie', 'Peterson', 238, 10),
 ('Mark', 'Webber', 17, 9),
 ('Jacky', 'Ickx', 235, 8),
 ('Denny', 'Hulme', 304, 8),
 ('René', 'Arnoux', 163, 7),
 ('Juan', 'Pablo Montoya', 31, 7),
 ('Jochen', 'Rindt', 358, 6),
 ('Riccardo', 'Patrese', 119, 6),
 ('Gilles', 'Villeneuve', 203, 6),
 ('Ralf', 'Schumacher', 23, 6),
 ('John', 'Surtees', 341, 6),
 ('Tony', 'Brooks', 479, 6),
 ('Jacques', 'Laffite', 172, 6),
 ('Michele', 'Alboreto', 105, 5),
 ('John', 'Watson', 187, 5),
 ('Nino', 'Farina', 642, 5),
 ('Clay', 'Regazzoni', 223, 5),
 ('Daniel', 'Ricciardo', 817, 5),
 ('Keke', 'Rosberg', 177, 5),
 ('Eddie', 'Irvine', 56, 4),
 ('Dan', 'Gurney', 364, 4),
 ('Bruce', 'McLaren', 360, 4),
 ('Heinz-Harald', 'Frentzen', 49, 3),
 ('Thierry', 'Boutsen', 123, 3),
 ('Johnny', 'Herbert', 65, 3),
 ('Didier', 'Pironi', 202, 3),
 ('Phil', 'Hill', 403, 3),
 ('Mike', 'Hawthorn', 578, 3),
 ('Giancarlo', 'Fisichella', 21, 3),
 ('Peter', 'Collins', 581, 3),
 ('Peter', 'Revson', 309, 2),
 ('Maurice', 'Trintignant', 427, 2),
 ('Elio', 'de Angelis', 173, 2),
 ('Patrick', 'Tambay', 175, 2),
 ('Jo', 'Siffert', 346, 2),
 ('Pedro', 'Rodríguez', 345, 2),
 ('Jean-Pierre', 'Jabouille', 219, 2),
 ('José Froilán', 'González', 498, 2),
 ('Max', 'Verstappen', 830, 2),
 ('Valtteri', 'Bottas', 822, 2),
 ('Wolfgang', 'von Trips', 476, 2),
 ('Patrick', 'Depailler', 221, 2),
 ('Bill', 'Vukovich', 657, 2),
 ('Vittorio', 'Brambilla', 230, 1),
 ('Sam', 'Hanks', 611, 1),
 ('Jim', 'Rathmann', 509, 1),
 ('Alessandro', 'Nannini', 145, 1),
 ('Heikki', 'Kovalainen', 5, 1),
 ('Gunnar', 'Nilsson', 255, 1),
 ('Jarno', 'Trulli', 15, 1),
 ('Jimmy', 'Bryan', 525, 1),
 ('Innes', 'Ireland', 404, 1),
 ('Pastor', 'Maldonado', 813, 1),
 ('Luigi', 'Fagioli', 786, 1),
 ('Rodger', 'Ward', 449, 1),
 ('Lee', 'Wallard', 766, 1),
 ('Peter', 'Gethin', 320, 1),
 ('Jean-Pierre', 'Beltoise', 306, 1),
 ('Jo', 'Bonnier', 347, 1),
 ('Robert', 'Kubica', 9, 1),
 ('Jochen', 'Mass', 200, 1),
 ('François', 'Cevert', 327, 1),
 ('Olivier', 'Panis', 44, 1),
 ('Richie', 'Ginther', 386, 1),
 ('Lorenzo', 'Bandini', 385, 1),
 ('Pat', 'Flaherty', 559, 1),
 ('Johnnie', 'Parsons', 593, 1),
 ('Giancarlo', 'Baghetti', 394, 1),
 ('Jean', 'Alesi', 55, 1),
 ('Ludovico', 'Scarfiotti', 375, 1),
 ('Carlos', 'Pace', 250, 1),
 ('Bob', 'Sweikert', 628, 1),
 ('Troy', 'Ruttman', 526, 1),
 ('Piero', 'Taruffi', 641, 1),
 ('Luigi', 'Musso', 577, 1)]

Ex2. Write a query that joins the tables results, constructors and drivers to show the amount of times a driver has driven a car from a constructor. In other words how many times one driver (for instance Schumacher) has driven a constructor (for instance Mercedes). Your table should have three fields: drivers.driverref, constructors.name and count(*) (showing the number of times the driver has driven the constructor).

In [136]:
%%sql SELECT drivers.driverref, constructors.name, count(*) 
FROM results 
JOIN drivers USING(driverid) 
JOIN constructors USING (constructorid) 
GROUP BY drivers.driverref, constructors.name 
ORDER BY count(*) DESC limit 50;

50 rows affected.

[('michael_schumacher', 'Ferrari', 181),
 ('coulthard', 'McLaren', 150),
 ('massa', 'Ferrari', 140),
 ('button', 'McLaren', 137),
 ('rosberg', 'Mercedes', 136),
 ('hakkinen', 'McLaren', 133),
 ('laffite', 'Ligier', 132),
 ('webber', 'Red Bull', 129),
 ('raikkonen', 'Ferrari', 126),
 ('vettel', 'Red Bull', 113),
 ('hamilton', 'McLaren', 110),
 ('prost', 'McLaren', 109),
 ('alonso', 'Renault', 106),
 ('martini', 'Minardi', 106),
 ('barrichello', 'Ferrari', 104),
 ('mansell', 'Williams', 97),
 ('senna', 'McLaren', 96),
 ('alonso', 'Ferrari', 96),
 ('berger', 'Ferrari', 96),
 ('ralf_schumacher', 'Williams', 94),
 ('hamilton', 'Mercedes', 93),
 ('sutil', 'Force India', 92),
 ('piquet', 'Brabham', 92),
 ('trulli', 'Toyota', 91),
 ('angelis', 'Team Lotus', 91),
 ('raikkonen', 'McLaren', 88),
 ('villeneuve', 'BAR', 82),
 ('patrese', 'Williams', 81),
 ('depailler', 'Tyrrell', 80),
 ('alboreto', 'Ferrari', 80),
 ('alesi', 'Ferrari', 79),
 ('hulkenberg', 'Force India', 79),
 ('bottas', 'Williams', 78),
 ('emerson_fittipaldi', 'Fittipaldi', 77),
 ('grosjean', 'Lotus F1', 76),
 ('watson', 'McLaren', 75),
 ('mario_andretti', 'Team Lotus', 75),
 ('ricciardo', 'Red Bull', 74),
 ('perez', 'Force India', 74),
 ('massa', 'Williams', 73),
 ('regazzoni', 'Ferrari', 73),
 ('ghinzani', 'Osella', 73),
 ('coulthard', 'Red Bull', 72),
 ('rosberg', 'Williams', 70),
 ('heidfeld', 'BMW Sauber', 70),
 ('alonso', 'McLaren', 69),
 ('michael_schumacher', 'Benetton', 68),
 ('montoya', 'Williams', 68),
 ('gilles_villeneuve', 'Ferrari', 67),
 ('frentzen', 'Sauber', 66)]

Ex3: Now we have found the most driven vehicles even for those who didn't finish the race. Extend the query from 2 by removing all tuples from the result where the status is not "Finished".

In [134]:
%%sql SELECT drivers.driverref, constructors.name, count(*) 
FROM results 
JOIN drivers USING(driverid) 
JOIN constructors USING (constructorid) 
JOIN status USING(statusid) 
WHERE status = 'Finished' 
GROUP BY drivers.driverref, constructors.name 
ORDER BY count(*) DESC limit 50;

50 rows affected.

[('michael_schumacher', 'Ferrari', 141),
 ('massa', 'Ferrari', 112),
 ('rosberg', 'Mercedes', 109),
 ('webber', 'Red Bull', 100),
 ('vettel', 'Red Bull', 97),
 ('raikkonen', 'Ferrari', 92),
 ('button', 'McLaren', 87),
 ('alonso', 'Ferrari', 87),
 ('coulthard', 'McLaren', 85),
 ('hamilton', 'Mercedes', 85),
 ('hamilton', 'McLaren', 84),
 ('alonso', 'Renault', 80),
 ('barrichello', 'Ferrari', 73),
 ('hakkinen', 'McLaren', 70),
 ('prost', 'McLaren', 69),
 ('senna', 'McLaren', 61),
 ('ricciardo', 'Red Bull', 56),
 ('ralf_schumacher', 'Williams', 54),
 ('bottas', 'Williams', 52),
 ('raikkonen', 'McLaren', 52),
 ('hulkenberg', 'Force India', 49),
 ('vettel', 'Ferrari', 48),
 ('heidfeld', 'BMW Sauber', 47),
 ('mansell', 'Williams', 46),
 ('michael_schumacher', 'Benetton', 44),
 ('damon_hill', 'Williams', 43),
 ('trulli', 'Toyota', 42),
 ('massa', 'Williams', 41),
 ('lauda', 'Ferrari', 40),
 ('patrese', 'Williams', 39),
 ('laffite', 'Ligier', 39),
 ('montoya', 'Williams', 39),
 ('kubica', 'BMW Sauber', 39),
 ('perez', 'Force India', 38),
 ('regazzoni', 'Ferrari', 37),
 ('irvine', 'Ferrari', 36),
 ('piquet', 'Brabham', 36),
 ('rosberg', 'Williams', 36),
 ('resta', 'Force India', 34),
 ('michael_schumacher', 'Mercedes', 34),
 ('sutil', 'Force India', 33),
 ('raikkonen', 'Lotus F1', 33),
 ('grosjean', 'Lotus F1', 33),
 ('fisichella', 'Renault', 33),
 ('depailler', 'Tyrrell', 32),
 ('berger', 'Ferrari', 31),
 ('berger', 'McLaren', 30),
 ('alonso', 'McLaren', 29),
 ('jones', 'Williams', 29),
 ('kobayashi', 'Sauber', 28)]

Ex4: Create a third (and new) query that finds the amount of milliseconds spent in pitstop (see the pitstops relation) by each unique combinations of driverid and raceid.

In [103]:
%sql SELECT driverid, raceid, SUM(milliseconds) FROM pitstops GROUP BY driverid, raceid ORDER BY SUM(milliseconds) limit 50;

50 rows affected.

[(154, 909, Decimal('18928')),
 (17, 877, Decimal('19066')),
 (4, 877, Decimal('19368')),
 (18, 877, Decimal('19455')),
 (155, 877, Decimal('19529')),
 (13, 877, Decimal('19585')),
 (18, 871, Decimal('19668')),
 (822, 955, Decimal('19732')),
 (10, 877, Decimal('19884')),
 (3, 955, Decimal('20058')),
 (1, 955, Decimal('20108')),
 (30, 864, Decimal('20113')),
 (18, 886, Decimal('20212')),
 (814, 858, Decimal('20216')),
 (30, 856, Decimal('20238')),
 (8, 877, Decimal('20278')),
 (814, 867, Decimal('20295')),
 (807, 955, Decimal('20347')),
 (20, 955, Decimal('20422')),
 (8, 955, Decimal('20593')),
 (815, 955, Decimal('20614')),
 (20, 876, Decimal('20707')),
 (813, 877, Decimal('20723')),
 (1, 872, Decimal('20736')),
 (1, 977, Decimal('20761')),
 (808, 877, Decimal('20769')),
 (825, 955, Decimal('20772')),
 (4, 876, Decimal('20800')),
 (17, 876, Decimal('20808')),
 (20, 871, Decimal('20811')),
 (1, 878, Decimal('20814')),
 (1, 876, Decimal('20852')),
 (20, 878, Decimal('20904')),
 (18, 850, Decimal('20952')),
 (154, 876, Decimal('20976')),
 (13, 977, Decimal('20977')),
 (814, 886, Decimal('21066')),
 (13, 876, Decimal('21100')),
 (4, 866, Decimal('21133')),
 (813, 875, Decimal('21137')),
 (154, 878, Decimal('21190')),
 (830, 968, Decimal('21221')),
 (24, 858, Decimal('21247')),
 (815, 874, Decimal('21273')),
 (818, 867, Decimal('21303')),
 (840, 977, Decimal('21332')),
 (1, 979, Decimal('21338')),
 (3, 878, Decimal('21346')),
 (820, 886, Decimal('21374')),
 (824, 886, Decimal('21378'))]

Ex5: Time to put everything together. Use the query for 4 as a join subquery in query 3 (see slides on "a query within a query") to find the total amount of pitstop time, for each result in query 3

In [131]:
%%sql SELECT drivers.driverref, constructors.name, ex4.sum, count(*)
FROM results 
INNER JOIN drivers USING(driverid) 
INNER JOIN constructors USING (constructorid) 
INNER JOIN status USING(statusid) 
INNER JOIN ex4 USING (driverid)
WHERE status = 'Finished' 
GROUP BY drivers.driverref, constructors.name, ex4.sum
ORDER BY count(*) DESC limit 50;

35 rows affected.

[('massa', 'Ferrari', Decimal('19585'), 112),
 ('rosberg', 'Mercedes', Decimal('20058'), 109),
 ('webber', 'Red Bull', Decimal('19066'), 100),
 ('button', 'McLaren', Decimal('19668'), 87),
 ('alonso', 'Ferrari', Decimal('19368'), 87),
 ('button', 'McLaren', Decimal('19455'), 87),
 ('alonso', 'Renault', Decimal('19368'), 80),
 ('bottas', 'Williams', Decimal('19732'), 52),
 ('massa', 'Williams', Decimal('19585'), 41),
 ('rosberg', 'Williams', Decimal('20058'), 36),
 ('grosjean', 'Lotus F1', Decimal('18928'), 33),
 ('alonso', 'McLaren', Decimal('19368'), 29),
 ('kobayashi', 'Sauber', Decimal('19529'), 28),
 ('button', 'BAR', Decimal('19455'), 27),
 ('button', 'BAR', Decimal('19668'), 27),
 ('glock', 'Toyota', Decimal('19884'), 22),
 ('button', 'Honda', Decimal('19668'), 19),
 ('button', 'Honda', Decimal('19455'), 19),
 ('button', 'Brawn', Decimal('19668'), 16),
 ('button', 'Brawn', Decimal('19455'), 16),
 ('bottas', 'Mercedes', Decimal('19732'), 14),
 ('webber', 'Williams', Decimal('19066'), 13),
 ('massa', 'Sauber', Decimal('19585'), 13),
 ('grosjean', 'Haas F1 Team', Decimal('18928'), 11),
 ('webber', 'Jaguar', Decimal('19066'), 8),
 ('button', 'Renault', Decimal('19668'), 6),
 ('button', 'Renault', Decimal('19455'), 6),
 ('button', 'Williams', Decimal('19455'), 4),
 ('button', 'Williams', Decimal('19668'), 4),
 ('button', 'Benetton', Decimal('19455'), 2),
 ('kobayashi', 'Toyota', Decimal('19529'), 2),
 ('glock', 'Marussia', Decimal('19884'), 2),
 ('button', 'Benetton', Decimal('19668'), 2),
 ('grosjean', 'Renault', Decimal('18928'), 1),
 ('kobayashi', 'Caterham', Decimal('19529'), 1)]

EX6: As a last thing we want to find the driver with the least pistop time. However we want to control for the amount of races (see explanation below), so we need to include one last column: the average pitstop time per race. Your table should be sorted based on the ascending values of that average pitstop time.

In [130]:
%%sql SELECT drivers.driverref, constructors.name, ex4.sum, ex4.sum/count(results.raceid) AS avg, count(*)
FROM results 
INNER JOIN drivers USING(driverid) 
INNER JOIN constructors USING (constructorid) 
INNER JOIN status USING(statusid) 
INNER JOIN ex4 USING (driverid)
WHERE status = 'Finished' 
GROUP BY drivers.driverref, constructors.name, ex4.sum
ORDER BY avg ASC limit 1;

1 rows affected.

[('massa', 'Ferrari', Decimal('19585'), Decimal('174.8660714285714286'), 112)]